language: python
python:
- '3.4'

before_install:
- pip install --disable-pip-version-check --upgrade pip
- openssl aes-256-cbc -K $encrypted_c7d371b9a595_key -iv $encrypted_c7d371b9a595_iv
  -in .private/deploy_key.enc -out deploy_key -d

install:
- pip install -r ./scripts/requirements.txt

script:
- python -m pytest ./scripts/tests
- ./scripts/generators/html/deploy-site.sh

env:
  global:
  - COMMIT_AUTHOR_EMAIL: "beardypig@protonmail.com"
